title = "Don't panic, impl Things"
description = "match x { \"Martijn Gribnau\" => blog!(), _ => open!(\"github.com/foresterre\") } "
theme = "blauwdruk"
author = "Martijn Gribnau"

# The URL the site will be built for
base_url = "https://gribnau.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
default_language = "en"

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [{ name = "tags", lang = "en", rss = true }]

generate_feeds = true

[markdown.highlighting]
theme = "material-theme-ocean"

[link_checker]
# Only report rotted links instead of failing on `zola check`
external_level = "warn"


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
keywords = "foresterre, rust, cargo-msrv, msrv, software engineering"

search_enabled = false

image_resizing_disabled = false
image_format = "auto"           # "auto", "jpg", "png", "webp"

# responsive image shortcode
# example: {{ image(src="foo.jpeg", alt="some image") }}
image_quality = 80
images_default_size = 1024
images_sizes = [512, 1024, 2048]

thumbnail_quality = 70
thumbnail_default_size = 256
thumbnail_sizes = [128, 256]

link_github_username = "foresterre"
# link_bluesky_username = ""
link_linkedin_username = "martijn-gribnau"

[extra.blauwdruk]
author = "Martijn Gribnau"
masthead = true
colophon = true
menu = [
    { name = "Index", url = "/" },
    { name = "Writing", url = "/posts/" },
    { name = "Projects", url = "/projects/" },
    { name = "GitHub⤴", url = "https://github.com/foresterre" },
]

github_username = "foresterre"

active_projects = [
    { name = "cargo-msrv", featured = true },
    { name = "rust-releases", featured = true },
    { name = "yare", featured = true },
    { name = "imagineer", featured = true },
    { name = "parameterized" },
    { name = "bisector" },
    { name = "busybar-rust" },
    { name = "storyteller" },
]

passive_projects = [
    { name = "cargo-api" },
    { name = "cargo-features" },
    { name = "commondir" },
    { name = "fallback-if" },
    { name = "faraday" },
    { name = "flammkuchen" },
    { name = "greenhouse" },
    { name = "intersection" },
    { name = "miniview" },
    { name = "peekmore" },
    { name = "phenomenon" },
    { name = "rust-toolchain-file" },
    { name = "sif" },
    { name = "version-number" },
]

archived_projects = [
    { name = "cargo-publish-workspace" },
    { name = "combostew" },
    { name = "exit-with-code" },
    { name = "jsonlines" },
    { name = "machinarium_saver" },
    { name = "reddold" },
    { name = "stew" },

]

fun_projects = [
    { name = "advent-of-code-2017"},
    { name = "advent-of-code-2018"},
    { name = "advent-of-code-2019"},
    { name = "advent-of-code-2020"},
    { name = "advent-of-code-2021"},
    { name = "advent-of-code-2022"},
    { name = "advent-of-code-2023"},
    { name = "advent-of-code-2024"},
    { name = "advent-of-code-2025"},
    { name = "linearsort" },
    { name = "reading-list" },
    { name = "random_challenges" },
    { name = "remarkable-articles" },
]

[extra.waystation]
articles_section = "posts/_index.md"
menu = [
    { name = "Home", path = "@/_index.md" },
    { name = "Posts", path = "@/posts/_index.md" },
    { name = "Tags", path = "tags/" },
    { name = "GitHub⤴", path = "https://github.com/foresterre" },
]
