title = "Foresterre"
description = "A cozy little blog"
base_url = "https://foresterre.github.io"

theme = "hyde"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = "theme-base-08"
hyde_links = [
    {url = "/", name = "Home"},
    {url = "/about", name = "About"},
    {url = "/blog", name = "Blog"},
    {url = "https://github.com/foresterre", name = "GitHub", projects = [
        {url = "https://github.com/foresterre/cargo-msrv", name = "Cargo MSRV"} # TODO add to templates/index.html <ul>
    ]},
]

custom_links = [
    {url = "/site", name = "site credits"}
]
